- type: entity
  id: BaseWound
  abstract: true
  components:
  - type: Wound
    damageToIntegrity: 0
    maxHealthDecrease: 0
    maxIntegrityDecrease: 0
- type: entity
  id: BaseHealingWound
  parent: BaseWound
  abstract: true
  components:
  - type: Healable




